# Reading HTML tables

In this lecture we'll learn how to read and parse HTML tables from websites into a list of `DataFrame` objects to work with.

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>


## Hands on!

In [1]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\terry\appdata\roaming\python\python313\site-packages (6.0.2)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>

## Parsing raw HTML strings

Another useful pandas method is `read_html()`. This method will read HTML tables from a given URL, a file-like object, or a raw string containing HTML, and return a list of `DataFrame` objects.

Let's try to read the following `html_string` into a `DataFrame`.

In [3]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [4]:
dfs = pd.read_html(html_string)

C:\Users\terry\AppData\Local\Temp\ipykernel_15932\2234146965.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html_string)

The `read_html` just returned one `DataFrame` object:

In [5]:
len(dfs)

1

In [6]:
df = dfs[0]

df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

Previous `DataFrame` looks quite similar to the raw HTML table, but now we have a `DataFrame` object, so we can apply any pandas operation we want to it.

In [7]:
df.shape

(4, 5)

In [8]:
df.loc[df['Region'] == 'Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [9]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

### Defining header

Pandas will automatically find the header to use thanks to the <thead> tag.
    
But in many cases we'll find wrong or incomplete tables that make the `read_html` method parse the tables in a wrong way without the proper headers.

To fix them we can use the `header` parameter.

In [10]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td> 
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td> 
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td> 
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td> 
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td> 
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [11]:
pd.read_html(html_string)[0]

C:\Users\terry\AppData\Local\Temp\ipykernel_15932\2877898795.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In this case, we'll need to pass the row number to use as header using the `header` parameter.

In [12]:
pd.read_html(html_string, header=0)[0]

C:\Users\terry\AppData\Local\Temp\ipykernel_15932\3156000096.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>


## Parsing HTML tables from the web

Now that we know how `read_html` works, go one step beyond and try to parse HTML tables directly from an URL.

To do that we'll call the `read_html` method with an URL as paramter.

In [13]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [14]:
nba_tables = pd.read_html(html_url)

In [15]:
len(nba_tables)

2

We'll work with the only one table found:

In [16]:
nba = nba_tables[0]

In [17]:
nba.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,James Harden,29.0,HOU,PG,78.0,78.0,36.8,10.8,24.5,...,0.8,5.8,6.6,7.5,2.0,0.7,5.0,3.1,36.1,"MVP-2,AS,NBA1"
1,2.0,Paul George,28.0,OKC,SF,77.0,77.0,36.9,9.2,21.0,...,1.4,6.8,8.2,4.1,2.2,0.4,2.7,2.8,28.0,"MVP-3,DPOY-3,AS,NBA1,DEF1"
2,3.0,Giannis Antetokounmpo,24.0,MIL,PF,72.0,72.0,32.8,10.0,17.3,...,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7,"MVP-1,DPOY-2,AS,NBA1,DEF1"
3,4.0,Joel Embiid,24.0,PHI,C,64.0,64.0,33.7,9.1,18.7,...,2.5,11.1,13.6,3.7,0.7,1.9,3.5,3.3,27.5,"MVP-7,DPOY-4,AS,NBA2,DEF2"
4,5.0,LeBron James,34.0,LAL,SF,55.0,55.0,35.2,10.1,19.9,...,1.0,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,"MVP-11,AS,NBA3"

### Complex example

We can also use the `requests` module to get HTML code from an URL to parse it into `DataFrame` objects.

If we look at the given URL we can see multiple tables about The Simpsons TV show.

We want to keep the table with information about each season.

In [18]:
import requests
from io import StringIO

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/141.0.0.0 Safari/537.36"
}

In [19]:
!pip install html5lib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: html5lib in c:\users\terry\appdata\roaming\python\python313\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\terry\appdata\roaming\python\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\terry\appdata\roaming\python\python313\site-packages (from html5lib) (0.5.1)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
r = requests.get(html_url,headers=headers)

wiki_tables = pd.read_html(StringIO(r.text), header=0)

print(f"✅ Found {len(wiki_tables)} tables")
display(wiki_tables[0].head())

✅ Found 50 tables

   The Simpsons                                     The Simpsons.1
0           NaN                                                NaN
1         Genre                             Animated sitcom Satire
2    Created by                                      Matt Groening
3  Developed by            James L. Brooks Matt Groening Sam Simon
4   Showrunners  James L. Brooks Matt Groening Sam Simon Al Jea...

In [21]:
len(wiki_tables)

50

In [22]:
Simpsons = wiki_tables[2]

In [23]:
Simpsons.head()

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Most watched episode,Most watched episode
1,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Viewers (millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][163],33.5[164],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[165],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[166],"""Colonel Homer"""

Quick clean on the table: remove extra header rows and set `Season` as index.

In [24]:
Simpsons.drop([0, 1], inplace=True)

In [26]:
Simpsons.set_index('Season', inplace=True)

Which season has the lowest number of episodes?

In [30]:
Simpsons['No. of episodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20', '18', '17'], dtype=object)

In [33]:
min_season = Simpsons['No. of episodes'].min()
min_season

'13'

In [38]:
Simpsons.loc[Simpsons['No. of episodes'] == min_season]

,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][163],33.5[164],"""Life on the Fast Lane"""

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>

In [ ]:
## Save to CSV file

Finally save the `DataFrame` to a CSV file as we saw on previous lectures.

In [35]:
Simpsons.head()

,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][163],33.5[164],"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[165],"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[166],"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][167],28.6[168],"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[169],"""Treehouse of Horror IV"""

In [36]:
Simpsons.to_csv('out.csv')

In [37]:
pd.read_csv('out.csv', index_col='Season').head()

,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][163],33.5[164],"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[165],"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[166],"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][167],28.6[168],"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[169],"""Treehouse of Horror IV"""

<div style="height:20px; background: linear-gradient(to right, #ff7e5f, #feb47b); border-radius:2px;"></div>